### ISSUE TITLE
Lỗi 

### ISSUE THREAD

**Issue by huukhoa1412** [demondvn/shardeum-node#1]
Step 11/11 : CMD ["./entrypoint.sh"]
 ---> Running in a134d84b159a
Removing intermediate container a134d84b159a
 ---> f64a70b184ef
Successfully built f64a70b184ef
Successfully tagged test-dashboard:latest

############################
# 5. Start Compose Project #
############################

How many instance you want (max 100): 2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    13  100    13    0     0     72      0 --:--:-- --:--:-- --:--:--    72
0
9001
10001
925eace37d1665e6df92269c02fc3046befa9a0bfafdecc5d8c23f56f388653a
Start shardeum-node-0 Success
1
9002
10002
ef9de3f8ca72f6a79d2f3fca1a4dee4013396efaf8772af2f3901cbba7da29a8
Start shardeum-node-1 Success
To run ./docker-up.sh number
Starting image. This could take a while...
Error: No such container: shardeum-dashboard
Error: No such container: shardeum-dashboard
root@vmi1126819:~/shardeum-node# cd

**Comment by demondvn** [comment]
Fixed !
